import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AddModal from "@/components/AddModal";
import Nav from "@/components/Navbar";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-neutral-950">
        <Nav />
        <AddModal />
        {children}

        <Toaster richColors closeButton />

      </body>
    </html>
  );
}
